# Generated by Django 4.0.4 on 2022-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='memberCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
