# Generated by Django 4.0.3 on 2022-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuitRef', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=10)),
                ('alt', models.DecimalField(decimal_places=5, max_digits=10)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructorRef', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverRef', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('forename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
