# Generated by Django 4.0.3 on 2022-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
