# Generated by Django 4.0.3 on 2022-03-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_driver_driverref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='circuitRef',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='constructorRef',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
